/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:d799ba54-5e20-4a90-8a3d-b7c9ee4eee86",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_7gnEwhykr",
    "aws_user_pools_web_client_id": "4a7ddf599hn66c9ll80008rip2",
    "oauth": {}
};


export default awsmobile;
